export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const PARTS_ROUTE = '/parts'
export const ACCESSORIES_ROUTE = '/accessories'
export const PC_ROUTE = '/pc'
export const CONFIGURATOR_ROUTE = '/configurator'